Repository SOPT-all/35-COLLABORATION-ANDROID-SAFETYREPORT, pull requests merged in 2024-11, with the labels that each got.

#2 [DOCS/#1] 리드미 추가
  README.md
Labels: DOCS :memo:, 석준 :rescue_worker_helmet:

#4 [ADD/#3] PR 템플릿 구현
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ADD :heavy_plus_sign:, 석준 :rescue_worker_helmet:

#7 [ADD/#6] 색상 시스템 추가
  app/src/main/java/com/sopt/shinmungo/MainActivity.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/color/Color.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/color/ShinMunGoColors.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/ShinMunGoTheme.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/Theme.kt
  app/src/main/java/com/sopt/shinmungo/ui/theme/Color.kt
  app/src/main/java/com/sopt/shinmungo/ui/theme/Theme.kt
  gradle/libs.versions.toml
Labels: ADD :heavy_plus_sign:, 석준 :rescue_worker_helmet:

#10 [ADD/#9] 라이브러리 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/shinmungo/ShinMunGoApplication.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ADD :heavy_plus_sign:, 석준 :rescue_worker_helmet:

#12 [ADD/#11] 프로젝트 최종 기초세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/shinmungo/core/designsystem/color/Color.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/ExampleText.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/Color.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/ShinMunGoTheme.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/Theme.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/Type.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/type/ShinMunGoTypography.kt
  app/src/main/java/com/sopt/shinmungo/core/extension/Modifier.kt
  app/src/main/java/com/sopt/shinmungo/core/state/UiState.kt
  app/src/main/java/com/sopt/shinmungo/data/dto/BaseResponse.kt
  app/src/main/java/com/sopt/shinmungo/data/dto/request/ExampleRequest.kt
  app/src/main/java/com/sopt/shinmungo/data/dto/response/ExampleResponse.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ApiFactory.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ServicePool.kt
  app/src/main/java/com/sopt/shinmungo/data/service/ExampleService.kt
  app/src/main/java/com/sopt/shinmungo/domain/entity/Example.kt
  app/src/main/java/com/sopt/shinmungo/domain/mapper/ExampleMapper.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/ExampleRepository.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/RepositoryPool.kt
  app/src/main/java/com/sopt/shinmungo/presentation/example/ExampleScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/example/ExampleViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/example/state/ExampleUiState.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainActivity.kt
Labels: ADD :heavy_plus_sign:, 석준 :rescue_worker_helmet:

#15 [UI/#14] 공통컴포넌트(dialog) 구현
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/dialog/CustomDialog.kt
  app/src/main/res/drawable/ic_close_24.xml
Labels: UI :iphone:, 재원 :rescue_worker_helmet:

#20 [UI/#17] 탑바 컴포넌트 구현
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/topbar/CommonTopBar.kt
  app/src/main/res/drawable/ic_arrow_left_line_white_24.xml
  app/src/main/res/drawable/ic_chat_line_white_24.xml
  app/src/main/res/drawable/ic_hammenu_line_white_24.xml
Labels: UI :iphone:, 황근 :rescue_worker_helmet:

#16 [FEAT/#13] 네비게이션 시스템 구현
  app/src/main/java/com/sopt/shinmungo/core/extension/Modifier.kt
  app/src/main/java/com/sopt/shinmungo/core/navigation/MainTabRoute.kt
  app/src/main/java/com/sopt/shinmungo/core/navigation/Route.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainActivity.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainNavigator.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainTab.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/component/MainBottomBars.kt
  app/src/main/res/drawable/ic_danger_24.xml
  app/src/main/res/drawable/ic_home_24.xml
  app/src/main/res/drawable/ic_news_24.xml
  app/src/main/res/drawable/ic_person_24.xml
  app/src/main/res/drawable/ic_safety_24.xml
  app/src/main/res/values/strings.xml
Labels: FEAT :sparkles:, 석준 :rescue_worker_helmet:

#19 [UI/#18] 버튼 컴포넌트 구현
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/CheckButtonWithTextInfoIcon.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundCornerIconButton.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundedCornerTextButton.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/TextWithInfoIcon.kt
  app/src/main/res/drawable/ic_checkbox_empty_16px.xml
  app/src/main/res/drawable/ic_checkbox_selected_16px.xml
  app/src/main/res/drawable/ic_info_circle_16px.xml
  app/src/main/res/drawable/ic_report_camera_24px.xml
  app/src/main/res/values/strings.xml
Labels: UI :iphone:, 채린 :rescue_worker_helmet:

#24 [FIX/#23] 타이포그래피 수정
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/Type.kt
Labels: HOTFIX :hammer_and_wrench:, 석준 :rescue_worker_helmet:

#26 [FEAT/#25] Explicit Backing Fields 관련 코틀린 옵션 추가
  app/build.gradle.kts
Labels: FEAT :sparkles:, 채린 :rescue_worker_helmet:

#34 [UI/#28] 주소 선택 UI 구현
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/map/AddressInputScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/map/AddressInputState.kt
  app/src/main/java/com/sopt/shinmungo/presentation/map/AddressInputViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/map/component/AddressCard.kt
  app/src/main/java/com/sopt/shinmungo/presentation/map/navigation/AddressNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/map/navigation/AddressRoute.kt
  app/src/main/res/drawable/ic_location_line_black_16px.xml
  app/src/main/res/drawable/img_map_placeholder.png
  app/src/main/res/values/strings.xml
Labels: UI :iphone:, 황근 :rescue_worker_helmet:

#32 [UI/#31] dialog 구현
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/dialog/CustomDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/FireTruckIllegalParkingDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/MediaSelectionDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/PhotoDeleteConfirmationDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/PhotoSizeLimitDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/PhotoTimeLimitDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/ResetConfirmationDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/SubmitCompleteDialog.kt
  app/src/main/res/drawable/icn_sound_white_24px.xml
  app/src/main/res/drawable/icon_alert_line_red_16px.xml
  app/src/main/res/drawable/mediaselection2.png
  app/src/main/res/drawable/parking3.png
  app/src/main/res/drawable/parking4.png
  app/src/main/res/values/strings.xml
Labels: UI :iphone:, 재원 :rescue_worker_helmet:

#29 [UI#27] 전체 카테고리(신고/View2)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/shinmungo/domain/entity/AllCategoryEntity.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/AllCategoryScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryTopBar.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/viewmodel/AllCategoryViewModel.kt
  app/src/main/res/values/strings.xml
Labels: UI :iphone:, 재원 :rescue_worker_helmet:

#33 [UI/#22] 신고페이지 UI 구현
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundCornerIconButton.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/Color.kt
  app/src/main/java/com/sopt/shinmungo/domain/entity/ReportPhotoItem.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/ReportViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/CategoryGrid.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/DropdownCategory.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportContentSection.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportLocationSection.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportPhoneNumberSection.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportPhotoSection.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportSectionTitle.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ShowPhotoList.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/type/ReportSectionType.kt
  app/src/main/res/drawable/ic_arrow_down_line_black_24px.xml
  app/src/main/res/drawable/ic_folder_line_black_24px.xml
  app/src/main/res/drawable/ic_report_copy_16px.xml
  app/src/main/res/drawable/ic_report_location_24px.xml
  app/src/main/res/drawable/ic_report_mic_24px.xml
  app/src/main/res/drawable/ic_report_orange_star.xml
  app/src/main/res/drawable/ic_report_trashcan_24px.xml
  app/src/main/res/values/strings.xml
Labels: UI :iphone:, 채린 :rescue_worker_helmet:

#30 [UI/#21] 홈화면 UI 구현
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/indicator/PageIndicator.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/progress/CommonProgressIndicator.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/text/ColorAnnotatedText.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/theme/Type.kt
  app/src/main/java/com/sopt/shinmungo/domain/entity/HomeInformation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/HomeScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/HomeFloatingActionButton.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/HomeImageBannerPager.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/HomeIssueExamplePager.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/HomeTopBar.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/button/BannerIconButton.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/group/CommonFloatingActionGroup.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/group/CommonReportGroup.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/group/HomeFloatingActionGroup.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/group/HomeMonthReportGroup.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/group/HomeYearReportGroup.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/state/HomeUiState.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/type/FloatingActionType.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainTab.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/component/MainBottomBars.kt
  app/src/main/res/drawable/ic_arrow_right_24.xml
  app/src/main/res/drawable/ic_car_24.xml
  app/src/main/res/drawable/ic_carwheel_24.xml
  app/src/main/res/drawable/ic_danger_filled_24.xml
  app/src/main/res/drawable/ic_graph_home_107.xml
  app/src/main/res/drawable/ic_home_filled_24.xml
  app/src/main/res/drawable/ic_logo_24.xml
  app/src/main/res/drawable/ic_menu_24.xml
  app/src/main/res/drawable/ic_news_filled_24.xml
  app/src/main/res/drawable/ic_next_home_10.xml
  app/src/main/res/drawable/ic_person_filled_24.xml
  app/src/main/res/drawable/ic_plus_16.xml
  app/src/main/res/drawable/ic_previous_home_10.xml
  app/src/main/res/drawable/ic_safety_filled_24.xml
  app/src/main/res/drawable/img_cases_1_after.png
  app/src/main/res/drawable/img_cases_1_before.png
  app/src/main/res/drawable/img_cases_2_after.png
  app/src/main/res/drawable/img_cases_2_before.png
  app/src/main/res/values/strings.xml
Labels: UI :iphone:, 석준 :rescue_worker_helmet:

#36 [UI/#35] 갤러리 화면 UI 구현
  app/src/main/java/com/sopt/shinmungo/domain/entity/Photo.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryDetailScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryState.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/component/AlertMessageBox.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/component/CustomTabRow.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/component/PhotoCard.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/component/PhotoDateTitle.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/navigation/GalleryNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/navigation/GalleryRoute.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainScreen.kt
  app/src/main/res/drawable/ic_alert_line_red_16.xml
  app/src/main/res/drawable/ic_checkbox_square_selected_white_24.xml
  app/src/main/res/drawable/ic_checkbox_square_unselected_white_24.xml
  app/src/main/res/drawable/img_gallery_example.png
  app/src/main/res/values/strings.xml
Labels: UI :iphone:, 황근 :rescue_worker_helmet:

#41 [FEAT/#38] 네비게이션 및 다이얼로그 관리
  app/build.gradle.kts
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/dialog/CustomDialog.kt
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/topbar/CommonTopBar.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ApiFactory.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/navigation/AllCategoryNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/FireTruckIllegalParkingDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/MediaSelectionDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/PhotoTimeLimitDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/SubmitConfirmDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryDetailScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/type/FloatingActionType.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainNavigator.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainTab.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/component/MainBottomBars.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/ReportViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/DropdownCategory.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportContentSection.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportDialogScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportPhoneNumberSection.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportPhotoSection.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ShowPhotoList.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/navigation/ReportNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/state/ReportDialogState.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/type/ReportDialogType.kt
  app/src/main/res/values/strings.xml
Labels: FEAT :sparkles:, 석준 :rescue_worker_helmet:

#43 [FEAT/#39] 갤러리 API 연결 구현
  app/src/main/java/com/sopt/shinmungo/data/dto/response/PhotoResponse.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ServicePool.kt
  app/src/main/java/com/sopt/shinmungo/data/service/GalleryService.kt
  app/src/main/java/com/sopt/shinmungo/data/util/LocalDateTimeSerializer.kt
  app/src/main/java/com/sopt/shinmungo/domain/mapper/PhotoMapper.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/GalleryRepository.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/RepositoryPool.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryViewModel.kt
Labels: FEAT :sparkles:, 황근 :rescue_worker_helmet:

#44 [FEAT/#37] 신고 카테고리 설명 조회 API 연결
  app/src/main/java/com/sopt/shinmungo/data/dto/response/AllCategoryResponse.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ApiFactory.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ServicePool.kt
  app/src/main/java/com/sopt/shinmungo/data/service/AllCategoryService.kt
  app/src/main/java/com/sopt/shinmungo/domain/mapper/AllCategoryMapper.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/AllCategoryRepository.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/ExampleRepository.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/RepositoryPool.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/AllCategoryScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/navigation/AllCategoryNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/viewmodel/AllCategoryViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/example/ExampleScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/example/ExampleViewModel.kt
Labels: FEAT :sparkles:, 재원 :rescue_worker_helmet:

#45 [FEAT/#42] 홈화면 api 연결
  app/src/main/java/com/sopt/shinmungo/data/dto/response/HomeInformationResponse.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ServicePool.kt
  app/src/main/java/com/sopt/shinmungo/data/service/HomeService.kt
  app/src/main/java/com/sopt/shinmungo/domain/entity/BannerImage.kt
  app/src/main/java/com/sopt/shinmungo/domain/entity/HomeInformation.kt
  app/src/main/java/com/sopt/shinmungo/domain/mapper/HomeInformationMapper.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/HomeRepository.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/RepositoryPool.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/HomeScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/HomeImageBannerPager.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainNavigator.kt
Labels: FEAT :sparkles:, 석준 :rescue_worker_helmet:

#46 [Feat/#40] 신고페이지 POST API 연결
  app/src/main/java/com/sopt/shinmungo/data/dto/request/ReportRequest.kt
  app/src/main/java/com/sopt/shinmungo/data/dto/response/ReportResponse.kt
  app/src/main/java/com/sopt/shinmungo/data/remote/ServicePool.kt
  app/src/main/java/com/sopt/shinmungo/data/service/ReportService.kt
  app/src/main/java/com/sopt/shinmungo/domain/entity/ReportPhotoItem.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/ReportRepository.kt
  app/src/main/java/com/sopt/shinmungo/domain/repository/RepositoryPool.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/ReportViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/CategoryGrid.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/DropdownCategory.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ShowPhotoList.kt
  app/src/main/res/values/strings.xml
Labels: FEAT :sparkles:, 채린 :rescue_worker_helmet:

#53 [FIX/#48] QA기반 오류 해결
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/AllCategoryScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryTopBar.kt
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/navigation/AllCategoryNavigation.kt
Labels: FIX :hammer:, 재원 :rescue_worker_helmet:

#51 [FIX/#50] 홈화면 QA 해결
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/navigation/AllCategoryNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/component/button/BannerIconButton.kt
  app/src/main/java/com/sopt/shinmungo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/MainNavigator.kt
  app/src/main/java/com/sopt/shinmungo/presentation/main/component/MainBottomBars.kt
  app/src/main/res/drawable/ic_home_24.xml
Labels: FIX :hammer:, 석준 :rescue_worker_helmet:

#52 [Fix/#49] 신고페이지 QA
  app/src/main/java/com/sopt/shinmungo/presentation/dialog/MediaSelectionDialog.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/ReportViewModel.kt
  app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportDialogScreen.kt
Labels: FIX :hammer:, 채린 :rescue_worker_helmet:

#54 [FIX/#47] 갤러리 화면 QA기반 오류 해결
  app/src/main/java/com/sopt/shinmungo/core/designsystem/component/topbar/CommonTopBar.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/navigation/GalleryNavigation.kt
  app/src/main/res/values/strings.xml
Labels: FIX :hammer:, 황근 :rescue_worker_helmet:

#56 [FIX/#55] 탑바 스타일 문제 해결
  app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryTopBar.kt
  app/src/main/java/com/sopt/shinmungo/presentation/gallery/GalleryDetailScreen.kt
Labels: FIX :hammer:, 황근 :rescue_worker_helmet:
